import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

// `kit/mv-icons.ts` imports `obsidian` (for addIcon), unresolvable under
// `node --test`. So these tests assert the module's invariants from its SOURCE
// text rather than importing it — the same source-reading pattern as
// release-contract.test.ts. They guard the icon registration contract.
//
// The module is GENERATED by marioverse-kit/mv-icons/generate.mjs. These tests
// are the check that a regeneration didn't silently change the contract, so
// they must keep passing without being loosened to fit a bad generation.
const source = readFileSync(new URL('../kit/mv-icons.ts', import.meta.url), 'utf8');

test('is generated, and says so', () => {
  assert.match(source, /GENERATO da marioverse-kit\/mv-icons/);
});

test('covers the core Lucide names Obsidian chrome draws', () => {
  // Overriding these is what re-skins menus, ribbon, navbar and settings.
  const required = [
    'search',
    'plus',
    'menu',
    'chevron-left',
    'chevron-right',
    'chevron-up',
    'chevron-down',
    'settings',
    'gear',
    'more-vertical',
    'more-horizontal',
    'calendar',
    'folder',
    'folder-open',
    'star',
    'trash',
    'copy',
    'link',
    'tag',
    'pencil',
    'arrow-left',
    'arrow-right',
    'check',
    'info',
  ];
  for (const key of required) {
    assert.ok(source.includes(`'${key}':`), `missing core-icon key: ${key}`);
  }
});

test('covers the custom names Portal has hard-coded in its own call sites', () => {
  // These are referenced by the ribbon, portal-view and the phone hub slots.
  // If a regeneration dropped one, those surfaces would render nothing.
  for (const key of ['hi-panel-left', 'hi-calendar', 'hi-file-01', 'hi-note-add', 'hi-task']) {
    assert.ok(source.includes(`'${key}':`), `missing custom-icon key: ${key}`);
  }
});

test('resolves the Lucide alias pairs to a single glyph each', () => {
  // The suite accumulated both spellings of the same concept over time
  // (Lucide renamed several icons). Both must be registered, or whichever
  // plugin used the older name would keep rendering the stock Lucide glyph
  // and visibly break the set.
  for (const [a, b] of [
    ['alert-triangle', 'triangle-alert'],
    ['ellipsis', 'more-horizontal'],
    ['loader', 'loader-2'],
  ]) {
    const pathA = source.match(new RegExp(`'${a}': '([^']+)'`))?.[1];
    const pathB = source.match(new RegExp(`'${b}': '([^']+)'`))?.[1];
    assert.ok(pathA, `missing alias key: ${a}`);
    assert.ok(pathB, `missing alias key: ${b}`);
    assert.equal(pathA, pathB, `alias pair ${a}/${b} must share one glyph`);
  }
});

test('every glyph is wrapped in the addIcon viewBox-safe transform', () => {
  // addIcon() forces viewBox "0 0 100 100", so each glyph needs a transform
  // mapping the set's native grid onto it. Material draws on a 960 grid whose
  // origin is y = -960: scaling alone would leave every glyph outside the box,
  // so the translate has to come first (SVG composes right-to-left).
  assert.match(source, /transform="\$\{TRANSFORM\}"/);
  assert.match(source, /const TRANSFORM = 'scale\(0\.1041667\) translate\(0 960\)'/);
  // The transform must be applied through the constant, never inlined per glyph.
  const inline = source.match(/<g transform="(?!\$\{TRANSFORM\})/g) ?? [];
  assert.deepEqual(inline, [], 'glyphs must share one transform constant');
});

test('path data reaches the DOM whole, never split', () => {
  // Regression guard. The generator used to `d.split(',')` to support
  // multi-path glyphs — but SVG path data is full of commas ("M208,32H48A16,16
  // 0 0 0…"), so every glyph was shredded into fragments and rendered corrupt.
  // The scale wrapper was still present, so a shape-only assertion passed while
  // the icons were broken. Assert the actual interpolation instead.
  assert.match(source, /<path d="\$\{d\}"\/>/, 'the whole `d` must be interpolated as one path');
  assert.ok(!/\bd\s*\.\s*split\(/.test(source), 'path data must never be split');

  // And the stored strings must themselves be plausible whole paths, not the
  // 4-character stumps the split bug produced.
  const values = [...source.matchAll(/^ {2}'[a-z0-9-]+': '([^']+)',$/gm)].map((m) => m[1] ?? '');
  assert.ok(values.length >= 100, `expected 100+ path entries, found ${values.length}`);
  for (const d of values) {
    assert.ok(d.length > 40, `suspiciously short path data (${d.length} chars): ${d}`);
  }
});

test('the CSS guard matches what the module actually emits', () => {
  // Regression guard. styles.css protects the glyphs from themes that style
  // `.svg-icon` for stroke-based Lucide (`fill: none`). That guard originally
  // keyed off the transform value — which is set-specific — so switching from
  // Phosphor to Material silently orphaned it: the rule was still there,
  // matching nothing. The marker attribute has to be the join between the two
  // files, and both sides have to agree on it.
  assert.match(source, /<g data-mv-icon transform=/, 'emitted glyphs must carry the marker');
  const css = readFileSync(new URL('../../styles.css', import.meta.url), 'utf8');
  assert.match(css, /\.svg-icon g\[data-mv-icon\]/, 'CSS must select on the marker');
  assert.ok(
    !/g\[transform=/.test(css),
    'CSS must not key off the transform value: it changes with the icon set',
  );
});

test('glyphs are solid (fill), not stroked', () => {
  // This is what makes the set read as "solid" — filled shapes, no outline.
  assert.match(source, /fill="currentColor"/);
  assert.ok(!source.includes('stroke='), 'solid set must not carry stroke attributes');
  assert.ok(!source.includes('fill="none"'), 'solid set must not carry fill="none"');
});

test('registers a broad set, not a token handful', () => {
  // A floor, not a target. How many Lucide names a set can cover depends on how
  // closely its vocabulary tracks Lucide's — Material's diverges more than
  // Phosphor's did, so the absolute number moves when the set changes. What
  // actually has to hold is the targeted coverage asserted in the two tests
  // below: the names this vault really draws.
  const keys = source.match(/^ {2}'[a-z0-9-]+':/gm) ?? [];
  assert.ok(keys.length >= 400, `expected 400+ registered names, found ${keys.length}`);
});

test('covers every Lucide name observed in this vault’s live chrome', () => {
  // Sampled from the real DOM (ribbon, tab bar, view header, editor toolbars).
  // A partial override is worse than none: it leaves a visible mix of filled
  // and outlined glyphs side by side, which is exactly the bug this closes.
  const inChrome = [
    'file-search', 'git-fork', 'wand-2', 'quote', 'terminal', 'terminal-square',
    'zoom-in', 'plane-takeoff', 'remove-formatting', 'sort-asc', 'layout-dashboard',
    'layout-list', 'list-ordered', 'message-square', 'move-vertical', 'strikethrough',
    'italic', 'bold', 'heading', 'tags', 'wrench', 'pin', 'send', 'eye', 'rotate-ccw',
  ];
  for (const key of inChrome) {
    assert.ok(source.includes(`'${key}':`), `missing chrome icon: ${key}`);
  }
});

test('exposes the install entry point and its diagnostics', () => {
  assert.match(source, /export function installMvIcons\(\): void/);
  assert.match(source, /export const MV_ICON_COUNT/);
  assert.match(source, /export function mvHasIcon/);
});

test('can repaint icons already in the DOM', () => {
  // addIcon() updates the registry but never the DOM, so anything drawn before
  // install stays on the old glyph for the whole session. Without this the
  // chrome built at startup never changes, no matter how many restarts.
  assert.match(source, /export function refreshRenderedIcons/);
  // It must key off Obsidian's `lucide-<name>` marker class...
  assert.match(source, /lucide-\(\[a-z0-9-\]\+\)/);
  // ...and swap the <svg> itself, never redraw onto the parent: many of those
  // parents also hold the button's label, which setIcon() would wipe.
  assert.match(source, /\.replaceWith\(fresh\)/);
  assert.ok(
    !/setIcon\(\s*svg\.parentElement/.test(source),
    'must not redraw onto the parent element',
  );
});

test('repaints icons in freshly rendered markdown', () => {
  // Obsidian draws the code-block "copy" button inline while rendering, not
  // through the icon registry, so overriding the registry never reaches it.
  // A markdown post processor runs exactly where those appear.
  const main = readFileSync(new URL('../main.ts', import.meta.url), 'utf8');
  assert.match(main, /registerMarkdownPostProcessor\(/);
  assert.match(main, /refreshRenderedIcons\(el\)/);
});

test('accepts a scoped root, so callers can repaint one subtree', () => {
  assert.match(source, /refreshRenderedIcons\(root: ParentNode = document\)/);
  // Guards against being handed something without a query API (a text node
  // from a post processor, a document fragment in an older Obsidian).
  assert.match(source, /typeof \(root as Element\)\.querySelectorAll !== 'function'/);
});

test('is mobile-safe: no Node/Electron builtins', () => {
  // The only import allowed is `obsidian` (addIcon). Portal runs on iPhone.
  const imports = source.match(/^import .*$/gm) ?? [];
  for (const line of imports) {
    assert.match(
      line,
      /from 'obsidian'/,
      `unexpected import (must be mobile-safe, obsidian-only): ${line}`,
    );
  }
  for (const banned of ['node:', 'electron', "require('fs", "require('path", 'process.']) {
    assert.ok(!source.includes(banned), `mobile-unsafe reference found: ${banned}`);
  }
});

test('the icon override ships off by default, and migrates existing installs', () => {
  // Portal is a public plugin. Overriding the icon registry changes glyphs far
  // outside Portal's own surface — Obsidian's chrome and other people's plugins
  // — and addIcon() has no runtime undo, so a default-on version could not be
  // taken back without restarting the app. Someone installing a sidebar plugin
  // has not asked for that.
  const settings = readFileSync(new URL('../settings.ts', import.meta.url), 'utf8');
  assert.match(settings, /mvIcons: false,/, 'mvIcons must default to false');
  // But an install that had the feature on under its old name must keep it.
  assert.match(settings, /data\.hugeCoreIcons/, 'legacy flag migration must survive');
});

test('third-party artwork is attributed', () => {
  // The glyphs are Apache-2.0 material redistributed inside main.js, in
  // modified form. That licence requires the notice, a copy of the licence,
  // and a statement of changes.
  const notice = readFileSync(new URL('../../NOTICE', import.meta.url), 'utf8');
  assert.match(notice, /Material Symbols/);
  assert.match(notice, /Apache License, Version 2\.0/);
  assert.match(notice, /MODIFICATIONS/);
  const apache = readFileSync(new URL('../../LICENSE-APACHE-2.0', import.meta.url), 'utf8');
  assert.match(apache, /Apache License/);
});

test('carries no Iconize dependency', () => {
  // The point of the migration: no runtime lookup against another plugin's
  // async, filesystem-backed icon cache.
  const internals = readFileSync(new URL('../obsidian-internals.ts', import.meta.url), 'utf8');
  assert.ok(
    !/getIconizeAssignment|renderIconizeIcon|setIconForNode/.test(internals),
    'Iconize runtime access must not come back',
  );
});
