import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

// `kit/mv-icons.ts` imports `obsidian` (for addIcon), unresolvable under
// `node --test`. So these tests assert the module's invariants from its SOURCE
// text rather than importing it — the same source-reading pattern as
// release-contract.test.ts. They guard the icon registration contract.
//
// The module is GENERATED by marioverse-kit/mv-icons/generate.mjs. These tests
// are the check that a regeneration didn't silently change the contract, so
// they must keep passing without being loosened to fit a bad generation.
const source = readFileSync(new URL('../kit/mv-icons.ts', import.meta.url), 'utf8');

test('is generated, and says so', () => {
  assert.match(source, /GENERATO da marioverse-kit\/mv-icons/);
});

test('covers the core Lucide names Obsidian chrome draws', () => {
  // Overriding these is what re-skins menus, ribbon, navbar and settings.
  const required = [
    'search',
    'plus',
    'menu',
    'chevron-left',
    'chevron-right',
    'chevron-up',
    'chevron-down',
    'settings',
    'gear',
    'more-vertical',
    'more-horizontal',
    'calendar',
    'folder',
    'folder-open',
    'star',
    'trash',
    'copy',
    'link',
    'tag',
    'pencil',
    'arrow-left',
    'arrow-right',
    'check',
    'info',
  ];
  for (const key of required) {
    assert.ok(source.includes(`'${key}':`), `missing core-icon key: ${key}`);
  }
});

test('covers the custom names Portal has hard-coded in its own call sites', () => {
  // These are referenced by the ribbon, portal-view and the phone hub slots.
  // If a regeneration dropped one, those surfaces would render nothing.
  for (const key of ['hi-panel-left', 'hi-calendar', 'hi-file-01', 'hi-note-add', 'hi-task']) {
    assert.ok(source.includes(`'${key}':`), `missing custom-icon key: ${key}`);
  }
});

test('resolves the Lucide alias pairs to a single glyph each', () => {
  // The suite accumulated both spellings of the same concept over time
  // (Lucide renamed several icons). Both must be registered, or whichever
  // plugin used the older name would keep rendering the stock Lucide glyph
  // and visibly break the set.
  for (const [a, b] of [
    ['alert-triangle', 'triangle-alert'],
    ['ellipsis', 'more-horizontal'],
    ['loader', 'loader-2'],
  ]) {
    const pathA = source.match(new RegExp(`'${a}': '([^']+)'`))?.[1];
    const pathB = source.match(new RegExp(`'${b}': '([^']+)'`))?.[1];
    assert.ok(pathA, `missing alias key: ${a}`);
    assert.ok(pathB, `missing alias key: ${b}`);
    assert.equal(pathA, pathB, `alias pair ${a}/${b} must share one glyph`);
  }
});

test('every glyph uses the addIcon viewBox-safe scale wrapper', () => {
  // 100 / 256 = 0.390625 — required because addIcon() forces viewBox
  // "0 0 100 100" while Phosphor draws on a 256 grid. Without it the glyphs
  // render ~2.5x oversized.
  assert.match(source, /scale\(\$\{SCALE\}\)/);
  assert.match(source, /const SCALE = '0\.390625'/);
  // No other, hard-coded scale factor may sneak in.
  const literals = source.match(/scale\(\d[^)]*\)/g) ?? [];
  assert.deepEqual(literals, [], `unexpected hard-coded transform scale: ${literals.join(', ')}`);
});

test('path data reaches the DOM whole, never split', () => {
  // Regression guard. The generator used to `d.split(',')` to support
  // multi-path glyphs — but SVG path data is full of commas ("M208,32H48A16,16
  // 0 0 0…"), so every glyph was shredded into fragments and rendered corrupt.
  // The scale wrapper was still present, so a shape-only assertion passed while
  // the icons were broken. Assert the actual interpolation instead.
  assert.match(source, /<path d="\$\{d\}"\/>/, 'the whole `d` must be interpolated as one path');
  assert.ok(!/\bd\s*\.\s*split\(/.test(source), 'path data must never be split');

  // And the stored strings must themselves be plausible whole paths, not the
  // 4-character stumps the split bug produced.
  const values = [...source.matchAll(/^ {2}'[a-z0-9-]+': '([^']+)',$/gm)].map((m) => m[1] ?? '');
  assert.ok(values.length >= 100, `expected 100+ path entries, found ${values.length}`);
  for (const d of values) {
    assert.ok(d.length > 40, `suspiciously short path data (${d.length} chars): ${d}`);
  }
});

test('glyphs are solid (fill), not stroked', () => {
  // This is what makes the set read as "solid" — filled shapes, no outline.
  assert.match(source, /fill="currentColor"/);
  assert.ok(!source.includes('stroke='), 'solid set must not carry stroke attributes');
  assert.ok(!source.includes('fill="none"'), 'solid set must not carry fill="none"');
});

test('registers a broad set, not a token handful', () => {
  const keys = source.match(/^ {2}'[a-z0-9-]+':/gm) ?? [];
  assert.ok(keys.length >= 100, `expected 100+ registered names, found ${keys.length}`);
});

test('exposes the install entry point and its diagnostics', () => {
  assert.match(source, /export function installMvIcons\(\): void/);
  assert.match(source, /export const MV_ICON_COUNT/);
  assert.match(source, /export function mvHasIcon/);
});

test('is mobile-safe: no Node/Electron builtins', () => {
  // The only import allowed is `obsidian` (addIcon). Portal runs on iPhone.
  const imports = source.match(/^import .*$/gm) ?? [];
  for (const line of imports) {
    assert.match(
      line,
      /from 'obsidian'/,
      `unexpected import (must be mobile-safe, obsidian-only): ${line}`,
    );
  }
  for (const banned of ['node:', 'electron', "require('fs", "require('path", 'process.']) {
    assert.ok(!source.includes(banned), `mobile-unsafe reference found: ${banned}`);
  }
});

test('carries no Iconize dependency', () => {
  // The point of the migration: no runtime lookup against another plugin's
  // async, filesystem-backed icon cache.
  const internals = readFileSync(new URL('../obsidian-internals.ts', import.meta.url), 'utf8');
  assert.ok(
    !/getIconizeAssignment|renderIconizeIcon|setIconForNode/.test(internals),
    'Iconize runtime access must not come back',
  );
});
